baseurl: "/black-white-blue"
theme: "black-white-blue"
project:
  name: "Black White Blue"
  subtitle: "A simple project page theme for Jekyll."
  description: ""
  repo: "crispgm/black-white-blue"
  logo: ""
  author: "David Zhang"
  author_link: "https://crispgm.com/"
highlightjs: true